### ISSUE TITLE
IPS mode pkt forward speed not increase as we increase thread number

### ISSUE THREAD

**Issue by Hotspot0Argus** [vipinpv85/DPDK_SURICATA-4_1_1#22]
We use the IPS mode in server which has 2 NUMA node(64 cores in total).We set different number of thread in suricata.yaml --> DPDK -->[port-config-*]-->queues:**xx**. But the pkt forward speed decreased when xx is 7(Max Speed is 11.16Mbps when xx is 6). And when xx is 12, we get "net_mlx5: port 1 Rx queue allocation failed: Cannot allocate memory". Is there some special config in yaml we missed?

some code of yaml are as follow:
```
threading:
  set-cpu-affinity: yes

  cpu-affinity:
    - management-cpu-set:
        cpu: [ 1 ]  # include only these CPUs in affinity settings
    - worker-cpu-set:
        cpu: [ "2-61" ]
        mode: "exclusive"
        # Use explicitely 3 threads and don't compute number by using
        # detect-thread-ratio variable:
        # threads: 3
        prio:
          high: [ "2-61" ]
          default: "high"

dpdk:

  pre-acl: yes
  post-acl: yes
  tx-fragment: no
  rx-reassemble: no
  tx-buffer: yes
  # BYPASS, IDS, IPS
  mode: IPS
  # port index
  input-output-map: [ "0-1", "1-0" ]
  # EAL args
  eal-args: [ "--log-level=eal,1", "-l 1", "--file-prefix=suricata-dpdk", "-m 40960"]
  # mempool
  mempool-port-common: [ name=suricata-port,n=24000,elt_size=2000,private_data_size=0 ]
  mempool-reas-common: [ name=suricatareassembly,n=8000,elt_size=10000,private_data_size=0 ]
  # port config
  port-config-0: [ mempool=portpool,queues=12,rss-tuple=14,ebpf=NULL,jumbo=no,mtu=1500 ]
  port-config-1: [ mempool=portpool,queues=12,rss-tuple=14,ebpf=NULL,jumbo=no,mtu=1500 ]
  #  port-config-2: [mempool=portpool,queues=4,rss-tuple=3,ebpf=NULL,jumbo=no,mtu=1500]
  #  port-config-3: [mempool=portpool,queues=4,rss-tuple=3,ebpf=NULL,jumbo=no,mtu=1500]
  # DPDK pre-acl
  ipv4-preacl: 10240
  ipv6-preacl: 10240

```
